language: python
python: 2.7
cache: apt
addons:
    apt:
        packages:
            - wkhtmltopdf

branches:
  only:
    - master

before_install:
	- wget https://raw.githubusercontent.com/infoeducatie/scripts/master/build_docs.py

install:
	- pip install boto
    - pip install pdfkit
    - pip install markdown

script:
    - python build_docs.py